"""baseline: 5 tables

Revision ID: 43bdce6c74a0
Revises: 
Create Date: 2026-03-26 11:24:47.150825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bdce6c74a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('lookback_min', sa.Integer(), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sound_file', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_dedup',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('symbol_age',
    sa.Column('symbol', sa.String(length=48), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('first_ts', sa.BigInteger(), nullable=False),
    sa.Column('first_day', sa.Date(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'category')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=48), nullable=False),
    sa.Column('size', sa.String(length=4), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('window', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_event_ts'), ['event_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_event_ts'))

    op.drop_table('signals')
    op.drop_table('symbol_age')
    op.drop_table('signal_dedup')
    op.drop_table('settings')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
