"""add settings_kv, drop settings

Revision ID: 6f1a3bf1a1c4
Revises: f4ab733d6fbc
Create Date: 2026-03-26 11:30:33.609893

"""
import json
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1a3bf1a1c4'
down_revision = 'f4ab733d6fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )

    # Migrate timezone value from old settings table
    conn = op.get_bind()
    row = conn.execute(sa.text("SELECT timezone FROM settings WHERE id = 1")).fetchone()
    if row:
        tz_val = row[0] or "UTC"
        now = datetime.now(timezone.utc).isoformat()
        conn.execute(
            sa.text("INSERT INTO settings_kv (key, value, updated_at) VALUES (:k, :v, :ts)"),
            {"k": "timezone", "v": json.dumps(tz_val), "ts": now},
        )

    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings_kv')
    # ### end Alembic commands ###
