"""drop Signal.size column

Revision ID: f4ab733d6fbc
Revises: 43bdce6c74a0
Create Date: 2026-03-26 11:28:41.045622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ab733d6fbc'
down_revision = '43bdce6c74a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=4), nullable=True))

    # ### end Alembic commands ###
